variables:
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"

cache:
  paths:
    - node_modules/

stages:
  - build
  - package
  - deploy

# build-supervision-server-data:
#   image: maven:3.5-jdk-8
#   stage: build
#   script:
#     - mvn clean verify -DskipTests $MAVEN_CLI_OPTS -f ./supervision-server-data/pom.xml
#   cache:
#     paths:
#       - ./.m2/repository
#     key: m2
#   artifacts:
#     paths:
#       - supervision-server-data/target/*.jar
#     expire_in: 1 week
#   tags:
#     - docker

# build-supervision-registry:
#   image: maven:3.5-jdk-8
#   stage: build
#   script:
#     - mvn clean verify -DskipTests $MAVEN_CLI_OPTS -f ./supervision-registry/pom.xml
#   cache:
#     paths:
#       - ./.m2/repository
#     key: m2
#   artifacts:
#     paths:
#       - supervision-registry/target/*.jar
#     expire_in: 1 week
#   tags:
#     - docker

# docker-build-supervision-registry:
#   image: docker:latest
#   stage: package
#   script:
#     - docker build -t registry.gitlab.com/augeo-software/supervision/supervision-registry ./supervision-registry
#     - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
#     - docker push registry.gitlab.com/augeo-software/supervision-registry
#   tags:
#     - docker

# Install sshpass in order to login to ssh prompt with password
before_script:
  - apt-get update -qq && apt-get install -y -qq sshpass

build-and-deploy-supervision-client:
  image: trion/ng-cli-karma
  stage: deploy
  environment: Staging
  only:
    - master
  script:
    - cd supervision-client
    - npm install
    - ./node_modules/@angular/cli/bin/ng build --progress false --env=qa
    - cd dist/
    - ls
    - sshpass -V
    # $USER_PASS variable is set in gitlab setting for CI / CD
    - export SSHPASS=$USER_PASS
    # If necessary (error on permission denied while copying files via scp)
    #- sudo chown -R admin:admin /path/to/files (to give rights to admin)
    - sshpass -e scp -o stricthostkeychecking=no -r . admin@home.f10web.com:/home/admin/supervision/supervision/supervision-client/dist

# run a nginx server for supervision
#  docker run --name nginx-sup-client -v /home/admin/supervision/supervision/supervision-client/dist:/usr/share/nginx/html:ro -it -p 4404:80 nginx
