server:
  port: 8762

eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 5 # DO NOT DO THIS IN PRODUCTION
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/