/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-spring-data-rest:src/main/java/repository/EntityRepository.java.e.vm
 */
package supervision.server.mail;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;

@RepositoryRestResource(collectionResourceRel = "mails", path = "mails")
public interface MailRepository extends JpaRepository<Mail, Long> {

    public List<Mail> findByEmailAddress(String emailAddress);

}